### ISSUE TITLE
Ubuntu PPA?

### ISSUE THREAD

**Issue by MatejKovacic** [danfruehauf/NetworkManager-ssh#51]
Hi,

this is really great software. Are there any plans to include it into official NetworkManager plugins? Or at least to create Ubuntu PPA, for simplier installation and updating?

Regards,

M.

**Comment by danfruehauf** [comment]
@MatejKovacic Good inquiry. Unfortunately I'm not using Ubuntu/debian at all. I provide complimentary debian/Ubuntu building help, but do not have the option to properly maintain it. I am the official maintainer of the Fedora package though (since I'm using Fedora). Would you like to be the one maintaining an Ubuntu PPA? I'm sure many people will thank you. I promise to help as much as possible.

**Comment by danfruehauf** [comment]
There are Ubuntu/Debian packages to the best of my knowledge, so I'm closing this one.
