### ISSUE TITLE
The 'ssh' plugin only supports a single active connection?

### ISSUE THREAD

**Issue by ehmar** [danfruehauf/NetworkManager-ssh#69]
Have been trying to figure out multiple active SSH connections (connecting to 2 different networks using ssh). Most issues I can find say multiple connections are available in NM 1.2, but I don't know if that's for ssh, or other plugins (openvpn, pptp, etc.). 

I'm using NM 1.6.2 w/ NM-ssh 1.2.1 on Debian Stretch. I can get both ssh vpns to connect individually, but never at the same time.

NM logs and nmcli both show "The 'ssh' plugin only supports a single active connection."

Is it possible for the ssh plugin to support multiple simultaneous connections? If not, can multiple connections be added?

Thanks,

**Comment by denisbutov** [comment]
Same problem in Fedora 26.

**Comment by danfruehauf** [comment]
Thanks for that. I have it on my TODO list. I actually already started development for it already. There shouldn't be a problem to support multiple connections with the plugin - it's a matter of getting the registration of the plugin right with NM (since multiple VPN connections is a new-ish feature of NM).

**Comment by ehmar** [comment]
Thanks for the update. I've been getting by with one NM/VPN and the other(s) over SSH/PPP http://www.faqs.org/docs/Linux-mini/ppp-ssh.html

**Comment by danfruehauf** [comment]
Closed by #73.

@lhw Probably worth releasing this one. I tagged it as 1.2.7.
